---

- name: "Configure auditd"
  hosts: all
  become: true
  tasks:
    - import_tasks: set-facts-with-defaults.yaml

    - name: "Disable auditd"
      include_tasks: tasks/disable-auditd.yaml
      when: not auditd_enabled

    - name: "Enable and configure auditd"
      when: auditd_enabled
      block:
      - include_tasks: tasks/enable-auditd.yaml
      - include_tasks: tasks/immutable-mode-check.yaml
      - include_tasks: tasks/retention.yaml
      - include_tasks: tasks/rules.yaml

    - include_tasks: tasks/grub/main.yaml

  handlers:
    - name: "systemd daemon reload"
      systemd:
        daemon_reload: true

    - name: "restart auditd"
      systemd:
        name: "{{ auditd_service }}"
        state: restarted
      when:
        - auditd_enabled
        - not immutable_mode_detected

    - name: "start auditd"
      become: true
      systemd:
        name: "{{ auditd_service }}"
        state: started
      when:
        - auditd_enabled
        - not immutable_mode_detected

    - name: Create /run/day2
      ansible.builtin.file:
        path: /run/day2
        state: directory
      listen: "request reboot"
      when: immutable_mode_detected

    - name: Update /run/day2/reboot-required with reboot reason
      ansible.builtin.lineinfile:
        path: "/run/day2/reboot-required"
        line: "Reboot is required by auditd: immutable mode detected, unable to restart auditd without reboot"
        create: true
      listen: "request reboot"
      when: immutable_mode_detected
