- service_facts:
  no_log: true

- name: "Ensure auditd service is stopped"
  systemd:
    name: "{{ auditd_service }}"
    enabled: false
    masked: true
    state: stopped
  when:
    - ansible_facts.services is contains(auditd_service)
    - ansible_facts.services[auditd_service].status is defined
    - ansible_facts.services[auditd_service].status != 'not-found'


- name: "Disable log compression cron task"
  file:
    path: "/etc/cron.daily/auditd.cron"
    state: absent
