---
- name: "Disable weekly offload cron task"
  ansible.builtin.file:
    path: "/etc/cron.weekly/audit-offload.cron"
    state: absent
  when: >
    (auditd_weekly_offload_enabled is not defined) or 
    (auditd_weekly_offload_enabled | default(false) == false)

- name: "Create weekly offload cron task"
  when:
    - auditd_weekly_offload_enabled is defined
    - auditd_weekly_offload_enabled | default(false) | bool
  block:
    - name: UBTU-24-900950 | Ensure rsync is installed
      ansible.builtin.package:
        name: rsync
        state: present

    - name: UBTU-24-900950 | Ensure root .ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0700'
      when: auditd_rsync_private_key is defined and auditd_rsync_private_key | length > 0

    - name: UBTU-24-900950 | Deploy private SSH key for offloading
      ansible.builtin.copy:
        dest: /root/.ssh/auditd_weekly_offload
        content: "{{ auditd_rsync_private_key }}"
        owner: root
        group: root
        mode: '0600'
      when: auditd_rsync_private_key is defined and auditd_rsync_private_key | length > 0

    - name: UBTU-24-900950 | Deploy weekly snapshot-style cron script from template
      ansible.builtin.template:
        src: audit-offload.sh.j2
        dest: /etc/cron.weekly/audit-offload.cron
        owner: root
        group: root
        mode: '0750'