---
- name: "Configure DISA STIG compliance settings"
  hosts: all
  become: true
  tasks:
    - when: values.enabled | default (False)
      block:
      - name: "Install required packages"
        include_tasks: tasks/packages.yaml

      - name: "Confidure sshd"
        include_tasks: tasks/sshd.yaml

      - name: "Confidure rsyslog"
        include_tasks: tasks/rsyslog.yaml

      - name: "Configure password quality"
        include_tasks: tasks/pwquality.yaml

      - name: "Configure common parameters"
        include_tasks: tasks/common.yaml

      - name: "Configure USB storage kernel module"
        include_tasks: tasks/usb.yaml

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted

    - name: Create /run/day2
      ansible.builtin.file:
        path: /run/day2
        state: directory
      listen: "request reboot"

    - name: Update /run/day2/reboot-required with reboot reason
      ansible.builtin.lineinfile:
        path: "/run/day2/reboot-required"
        line: "Reboot is required by disa-stig module."
        create: true
      listen: "request reboot"
