// Code generated by TestDocHelp; DO NOT EDIT.

// ModuleBuilder is a tool for managing host OS modules.
//
// Usage:
//
//	module-builder <command> [arguments]
//
// The commands are:
//
//	module	build archive(s) for module(s) and update the index.yaml
//	sort	sorts index-dev.yaml and index.yaml
package main
